### ISSUE TITLE
不能验证通过好友

### ISSUE THREAD

**Issue by klmmlk** [why2lyj/ItChat-UOS#5]
在提交前，请确保您已经检查了以下内容!

- [ ] 您可以在浏览器中登陆微信账号，但不能使用`itchat`登陆
- [ ] 我已经阅读并按[文档][document] 中的指引进行了操作
- [ ] 您的问题没有在[issues][issues]报告，否则请在原有issue下报告
- [ ] 本问题确实关于`itchat`, 而不是其他项目.
- [ ] 如果你的问题关于稳定性，建议尝试对网络稳定性要求极低的[itchatmp][itchatmp]项目

请使用`itchat.run(debug=True)`运行，并将输出粘贴在下面:

```
Start auto replying.
@b1ea7c607f098733b46498e1835a5d34
Request to send a text message to @b1ea7c607f098733b46498e1835a5d34: Nice to meet you!
{'BaseResponse': {'Ret': -1, 'ErrMsg': '', 'RawMsg': ''}}
```

您的itchat版本为：`1.4.1`。（可通过`python -c "import itchat;print(itchat.__version__)"`获取）

其他的内容或者问题更详细的描述都可以添加在下面：

>不能验证通过好友
代码如下：
import itchat
from itchat.content import *
if __name__ == '__main__':
    @itchat.msg_register(FRIENDS)
    def add_friend(msg):
        print(msg.user.UserName)
        # print(itchat.add_friend(msg.user.UserName, 3))
        print(msg.user.verify())
        msg.user.send('Nice to meet you!')
    itchat.auto_login(hotReload=True)
    itchat.run(debug=True)

上传代码缩进没有了，我贴一张图吧
![微信截图_20211204145159](https://user-images.githubusercontent.com/12571901/144700701-47334da4-9919-4df0-802e-5c3526af8cc9.png)
[document]: http://itchat.readthedocs.io/zh/latest/
[issues]: https://github.com/littlecodersh/itchat/issues
[itchatmp]: https://github.com/littlecodersh/itchatmp

**Comment by why2lyj** [comment]
@klmmlk 
请使用 `1.5.0.dev0` 版本，已修复至该版本
```python
pip install itchat-uos==1.5.0.dev0
```
