### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by Gary2018X** [why2lyj/ItChat-UOS#8]
无法登录
报错
core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

**Comment by mutecamel** [comment]
+1

**Comment by MeteorWs** [comment]
+1

**Comment by PPPChan** [comment]
+1

**Comment by Alex-Shang** [comment]
该方式被封禁了。。

**Comment by Crazy-Young** [comment]
File "C:\Users\wJc\AppData\Roaming\Python\Python38\site-packages\itchat\components\login.py", line 183, in process_login_info
    core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

**Comment by Crazy-Young** [comment]
core.loginInfo['wxsid'] = core.loginInfo['BaseRequest']['Sid'] = cookies["wxsid"]
KeyError: 'wxsid'

**Comment by why2lyj** [comment]
@Gary2018X @mutecamel @PPPChan @Alex-Shang @Crazy-Young 
请使用 `1.5.0.dev0` 版本
```python
pip install itchat-uos==1.5.0.dev0
```
